from django.shortcuts import render
from . models import Task
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
import json

# Create your views here.

# @csrf_exempt
# def home(request):
#     tasks = Task.objects.all()
#     return HttpResponse(tasks)

# A session in web development is a way to store data (such as user information) across multiple requests made by a user to a server. 
# Sessions allow you to maintain a state between different HTTP requests (which are stateless by nature).

# A session represents the period during which a user interacts with a web application. 
# Sessions are useful for keeping track of information like whether a user is logged in, 
# their preferences, shopping cart, etc., across multiple pages or requests.


# Sessions typically work like this:
# When a user logs into a website or interacts with it, a session is created on the server side.
# A session ID is generated and sent to the user's browser as a cookie.
# The session data is stored on the server and linked to the session ID.
# Every time the user makes a new request, the session ID is sent along with the request (via cookies), allowing the server to know which user the request belongs to.

# What is a Session ID?
# A session ID is a unique identifier generated by the server when a session is created. It is typically a long random string that acts as a "key" to retrieve session data stored on the server.

# The session ID is sent to the user's browser, usually stored as a cookie.
# The browser sends this session ID with every subsequent HTTP request, allowing the server to retrieve the correct session data and continue the interaction with the user.


@csrf_exempt
def add_task(request):
    if request.method == 'POST':
        print(request)
        print("Request headers: ",request.headers)
        print("User sessions: ", request.session)
        task = json.loads(request.body)
        print(task)
        title = task.get('title')
        body = task.get('body')
        user = request.user
        print(user)
        # user = request.user

        if user.is_authenticated:
            if title:
                task = Task.objects.create(title = title, body = body, user=user)
                task.save()
                return JsonResponse({'message' : 'Your task is added successfully :)'}, status = 200)
            else:
                return JsonResponse({'error' : 'Title is required'}, status = 400)
        
        else:
            return JsonResponse({'error' : 'This user is not authenticated :('})
        
    else:
        return JsonResponse({'error': 'Invalid request method'}, status = 405)
    

@csrf_exempt
def list_tasks(request, user_id):
    try:
        user = User.objects.get(id = user_id)
        tasks = Task.objects.filter(user = user) 
        tasks_list = list(tasks.values('title','body'))
        return JsonResponse({'tasks' : tasks_list}, status = 200)
    
    except User.DoesNotExist:
        return JsonResponse({'error' : "User not found"}, status = 404)


@csrf_exempt
def delete_task(request, task_id):
    task = Task.objects.get(id = task_id)
    task.delete()
    return HttpResponseRedirect('/')


@csrf_exempt
def edit_task(request, task_id):
    if request.method == 'POST':
        task = Task.objects.get(id = task_id)
        task.title = request.POST['title']
        task.body = request.POST['body'] 
        task.save() 

    elif request.method == 'GET':
        task = Task.objects.get(id = task_id)
        return HttpResponseRedirect('/')
